version: '3.0'
services:

  web:
    build: ./build/magento
    ports:
      - "9090:80"
    links:
      - db
    volumes:
      - ./www/html:/var/www/html
    env_file:
      - .env

  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9091:80"
    links:
      - db     
    env_file:
      - .env
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PHP_UPLOAD_MAX_FILESIZE=512MB
      
volumes:
  db-data: 